export const indonesianKeywords = [
  "SMK terbaik",
  "sekolah menengah kejuruan",
  "kurikulum merdeka",
  "pendidikan karakter",
  "sekolah unggulan",
  "PPDB SMK",
  "penerimaan siswa baru",
  "ekstrakurikuler SMK",
  "fasilitas sekolah modern",
  "prestasi siswa",
  "olimpiade sains",
  "sekolah terakreditasi A",
  "SMK Setia Karya",
];
